//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksLists
    {
        public int ID { get; set; }
        public int ListID { get; set; }
        public int BookID { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Lists Lists { get; set; }
    }
}
