//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Marinin_LibraryEntities : DbContext
    {
        public Marinin_LibraryEntities()
            : base("name=Marinin_LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<BooksGenres> BooksGenres { get; set; }
        public virtual DbSet<BooksLists> BooksLists { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Lists> Lists { get; set; }
        public virtual DbSet<ListTypes> ListTypes { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<ReportTypes> ReportTypes { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<RoleRequests> RoleRequests { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UnfreezeRequests> UnfreezeRequests { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
