//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int ReportID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public int TypeID { get; set; }
        public bool Solved { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual ReportTypes ReportTypes { get; set; }
        public virtual Reviews Reviews { get; set; }
        public virtual Users Users { get; set; }
    }
}
