//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnfreezeRequests
    {
        public int RequestID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public int TypeID { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual ReportTypes ReportTypes { get; set; }
        public virtual Reviews Reviews { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
